<?php

/**
 * @file
 * Module file for custom_user.
 */


/**
 * Implements hook_theme().
 *
 * We use hook_theme to define the templates used.
 */
function custom_user_theme($existing, $type, $theme, $path) {
  return [
    'custom' => [
      'variables' => [],
    ]
  ];
}


// function custom_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
//   /**
//    * Custom javascript for the search form
//    */
//   // if($form['#id'] == 'custom_user_details') {
//   //   $form['#attached']['library'][] = 'custom_user/customjsform';
//   // }
// }
